 server:
   port: 9090

 spring:
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/message?serverTimezone=UTC
     username: root
     password: 123123
   mail:
     host : smtp.qq.com
     username : 2514658052@qq.com
     password : wovknypvuqpgeabj
     properties:
       mail:
         smtp:
           ssl:
             enable: true
     default-encoding : UTF-8

 mybatis:
  mapper-locations: classpath:mapper/*.xml